// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/user","layout":false,"id":"2"},"3":{"name":"登录","path":"/user/login","parentId":"2","id":"3"},"4":{"name":"仪表盘","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"平台管理","path":"/platform","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"5"},"6":{"name":"模板管理","path":"/platform/template","parentId":"5","id":"6"},"7":{"name":"用户管理","path":"/platform/users","parentId":"5","id":"7"},"8":{"name":"商户管理","path":"/platform/vendors","parentId":"5","id":"8"},"9":{"name":"订单管理","path":"/platform/orders","parentId":"5","id":"9"},"10":{"name":"服务配置","path":"/platform/settings","parentId":"5","id":"10"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__user__login__index" */'@/pages/user/login/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__platform__dashboard__index" */'@/pages/platform/dashboard/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import(/* webpackChunkName: "p__platform__template__index" */'@/pages/platform/template/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__platform__users__index" */'@/pages/platform/users/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__platform__vendors__index" */'@/pages/platform/vendors/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__platform__orders__index" */'@/pages/platform/orders/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__platform__settings__index" */'@/pages/platform/settings/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
