// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@19.3.0_react@19.3.0__react@19.3.0/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, SettingOutlined };
