// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-access';
export { useAntdConfig, useAntdConfigSetter } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-antd';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-locale';
export { Provider, useModel } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-access/types.d';
export * from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-antd/types.d';
export * from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-layout/types.d';
export * from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/node_modules/.pnpm/@umijs+renderer-react@4.7.18_react-dom@18.3.1_react@18.3.1__react@18.3.1_supports-color@8.1.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/node_modules/.pnpm/@umijs+renderer-react@4.7.18_react-dom@18.3.1_react@18.3.1__react@18.3.1_supports-color@8.1.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/opt/1panel/www/sites/sunlyvo.com/index/wp-content/themes/sunlyvo-nexus/src/node_modules/.pnpm/umi@4.7.18_@babel+core@7.29.7_supports-color@8.1.1__@types+node@22.20.3_@types+react@19_1a40560f6ac40440030776e769ee0b0c/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
