allowBuilds:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - sharp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - sharp

auto-install-peers: true
strict-peer-dependencies: false